### ISSUE TITLE
pcase not recognizing that variable is bound with `loopy-iter`

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#69] opened 2021-04-18 19:38 UTC
Note that I aliased `loopy-iter` to `iter`. The same thing happens if I just use `loopy-iter`.

```elisp
(defun use-package-normalize/:advice (_ _ advices)
  "Ensure that ADVICES is a list of advice arguments.
ADVICES should be of the form (WHERE SYMBOL ADVICE PROPS EXPIRE-FN) where PROPS
and EXPIRE-FN are optional."
  (iter (each elt advices)
	(pcase elt
	  (`(,(and (pred keywordp) key) (,fn . ,advice))
	   (collect (list key fn advice)))
	  (`(,fn . ,advice)
	   (collect (list :around fn advice)))
	  (_
	   (error "wrong args"))))

  ;; If I replace the body with the following it works.
  ;; (let (collection)
  ;;   (dolist (elt advices)
  ;;     (pcase elt
  ;; 	(`(,(and (pred keywordp) key) (,fn . ,advice))
  ;; 	 (push (list key fn advice) collection))
  ;; 	(`(,fn . ,advice)
  ;; 	 (push (list :around fn advice) collection))
  ;; 	(_
  ;; 	 (error "wrong args"))))
  ;;   (nreverse collection))
  )
```

Full Backtrace:

```elisp
Debugger entered--Lisp error: (void-variable elt)
  (consp elt)
  (let* ((--dash-source-39-- nil) (pcase-0 (pop --dash-source-39--)) (--dash-source-40-- (car --dash-source-39--)) #'(pop --dash-source-40--) (--dash-source-41-- (car --dash-source-40--)) (lambda (pop --dash-source-41--)) (--dash-source-42-- (pop --dash-source-41--)) (advice (pop --dash-source-42--)) (fn (car --dash-source-42--)) (--dash-source-43-- (car --dash-source-41--)) (collect (pop --dash-source-43--)) (--dash-source-44-- (car --dash-source-43--)) (list (pop --dash-source-44--)) (:around (pop --dash-source-44--)) (fn (pop --dash-source-44--)) (advice (car --dash-source-44--)) (if (consp elt))) (let ((loopy-result nil)) (let* ((list-2032 advices) (elt nil)) (cl-block nil (while (consp list-2032) (setq elt (car list-2032)) (let* ((pcase-0 ...)) (if (consp elt) (let* ... ...) (error "wrong args"))) (setq list-2032 (cdr list-2032))) (setq loopy-result (nreverse loopy-result)) loopy-result))))
  (-let* (((pcase-0 #'(lambda (advice fn) (collect (list :around fn advice)))) nil) (if (consp elt) (let* ((x52 (car elt))) (if (keywordp x52) (let* ((x53 ...)) (if (consp x53) (let* ... ...) (funcall pcase-0 x53 x52))) (let* ((x58 ...)) (funcall pcase-0 x58 x52)))) (error "wrong args"))) (let ((loopy-result nil)) (let* ((list-2032 advices) (elt nil)) (cl-block nil (while (consp list-2032) (setq elt (car list-2032)) (let* ((pcase-0 ...)) (if (consp elt) (let* ... ...) (error "wrong args"))) (setq list-2032 (cdr list-2032))) (setq loopy-result (nreverse loopy-result)) loopy-result))))
  (iter (each elt advices) (let* ((pcase-0 #'(lambda (advice fn) (collect (list :around fn advice))))) (if (consp elt) (let* ((x52 (car elt))) (if (keywordp x52) (let* ((x53 ...)) (if (consp x53) (let* ... ...) (funcall pcase-0 x53 x52))) (let* ((x58 ...)) (funcall pcase-0 x58 x52)))) (error "wrong args"))))
  use-package-normalize/:advice(elisp-demos :advice ((:after (helpful-update . elisp-demos-advice-helpful-update))))
  use-package-normalize-plist(elisp-demos (:advice (:after (helpful-update . elisp-demos-advice-helpful-update))) nil use-package-merge-keys)
  use-package-normalize-keywords(elisp-demos (:advice (:after (helpful-update . elisp-demos-advice-helpful-update))))
  #f(compiled-function (name &rest args) "Declare an Emacs package by specifying a group of configuration options.\n\nFor full documentation, please see the README file that came with\nthis file.  Usage:\n\n  (use-package package-name\n     [:keyword [option]]...)\n\n:init            Code to run before PACKAGE-NAME has been loaded.\n:config          Code to run after PACKAGE-NAME has been loaded.  Note that\n                 if loading is deferred for any reason, this code does not\n                 execute until the lazy load has occurred.\n:preface         Code to be run before everything except `:disabled'; this\n                 can be used to define functions for use in `:if', or that\n                 should be seen by the byte-compiler.\n\n:mode            Form to be added to `auto-mode-alist'.\n:magic           Form to be added to `magic-mode-alist'.\n:magic-fallback  Form to be added to `magic-fallback-mode-alist'.\n:interpreter     Form to be added to `interpreter-mode-alist'.\n\n:commands        Define autoloads for commands that will be defined by the\n                 package.  This is useful if the package is being lazily\n                 loaded, and you wish to conditionally call functions in your\n                 `:init' block that are defined in the package.\n:hook            Specify hook(s) to attach this package to.\n\n:bind            Bind keys, and define autoloads for the bound commands.\n:bind*           Bind keys, and define autoloads for the bound commands,\n                 *overriding all minor mode bindings*.\n:bind-keymap     Bind a key prefix to an auto-loaded keymap defined in the\n                 package.  This is like `:bind', but for keymaps.\n:bind-keymap*    Like `:bind-keymap', but overrides all minor mode bindings\n\n:defer           Defer loading of a package -- this is implied when using\n                 `:commands', `:bind', `:bind*', `:mode', `:magic', `:hook',\n                 `:magic-fallback', or `:interpreter'.  This can be an integer,\n                 to force loading after N seconds of idle time, if the package\n                 has not already been loaded.\n:after           Delay the use-package declaration until after the named modules\n                 have loaded. Once load, it will be as though the use-package\n                 declaration (without `:after') had been seen at that moment.\n:demand          Prevent the automatic deferred loading introduced by constructs\n                 such as `:bind' (see `:defer' for the complete list).\n\n:if EXPR         Initialize and load only if EXPR evaluates to a non-nil value.\n:disabled        The package is ignored completely if this keyword is present.\n:defines         Declare certain variables to silence the byte-compiler.\n:functions       Declare certain functions to silence the byte-compiler.\n:load-path       Add to the `load-path' before attempting to load the package.\n:diminish        Support for diminish.el (if installed).\n:delight         Support for delight.el (if installed).\n:custom          Call `custom-set' or `set-default' with each variable\n                 definition without modifying the Emacs `custom-file'.\n                 (compare with `custom-set-variables').\n:custom-face     Call `customize-set-faces' with each face definition.\n:ensure          Loads the package using package.el if necessary.\n:pin             Pin the package to an archive." #<bytecode 0xdc8da5>)(elisp-demos :advice (:after (helpful-update . elisp-demos-advice-helpful-update)))
  macroexpand((use-package elisp-demos :advice (:after (helpful-update . elisp-demos-advice-helpful-update))))
  internal-macroexpand-for-load((use-package elisp-demos :advice (:after (helpful-update . elisp-demos-advice-helpful-update))) nil)
  eval-buffer(#<buffer  *load*> nil "/home/luis/.config/emacs/init.el" nil t)  ; Reading at buffer position 100319
  load-with-code-conversion("/home/luis/.config/emacs/init.el" "/home/luis/.config/emacs/init.el" t t)
  load("/home/luis/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0xac78bd>) #f(compiled-function () #<bytecode 0xac78d1>) t)
  command-line()
  normal-top-level()
```

**Comment by Luis-Henriquez-Perez** [comment] 2021-04-18 20:38
I will note, that putting a `progn` around the `pcase` causes it to work as expected

**Comment by okamsn** [comment] 2021-04-20 03:54
Could you give the values you're using for `advices`? Also, could you give the full expansion of the macro? Below is a wrapper around `macroexpand-all`. I don't see why you're getting references to Dash if you didn't perform any destructuring with it.

``` elisp
(defun my-pp-macroexpand-all-last-sexp (arg)
  "Like `pp-macroexpand-last-sexp', but use `macroexpand-all'.
With ARG, print into current buffer."
  (interactive "P")
  (if arg
      (insert (pp-to-string (macroexpand-all (pp-last-sexp))))
    (pp-display-expression (macroexpand-all (pp-last-sexp))
                           "*Pp Macroexpand Output*")))
```

For the record, when I expand

``` elisp
(loopy-iter
 (flag dash lax-naming)
 (each elt advices)
 (pcase elt
   (`(,(and (pred keywordp) key) (,fn . ,advice))
    (collect (list key fn advice)))
   (`(,fn . ,advice)
    (collect (list :around fn advice)))
   (_
    (error "wrong args"))))
```

I get the following on Emacs 28 with the current Pcase destructuring method, which seems to have `let`-bound `elt` as expected.

``` elisp
(let ((loopy-result nil))
  (let* ((list-297 advices)
         (elt nil))
    (progn
      (while (consp list-297)
        (setq elt (car list-297))
        (let* ((pcase-0 #'(lambda
                            (fn advice)
                            (setq loopy-result
                                  (cons (list :around fn advice)
                                        loopy-result)))))
          (if (consp elt)
              (let* ((x290 (car-safe elt)))
                (if (keywordp x290)
                    (let* ((x291 (cdr-safe elt)))
                      (if (consp x291)
                          (let* ((x292 (car-safe x291)))
                            (if (consp x292)
                                (let* ((x293 (car-safe x292))
                                       (x294 (cdr-safe x292))
                                       (x295 (cdr-safe x291)))
                                  (if (null x295)
                                      (let ((key x290)
                                            (fn x293)
                                            (advice x294))
                                        (setq loopy-result
                                              (cons
                                               (list key fn advice)
                                               loopy-result)))
                                    (funcall pcase-0 x290 x291)))
                              (funcall pcase-0 x290 x291)))
                        (funcall pcase-0 x290 x291)))
                  (let* ((x296 (cdr-safe elt)))
                    (funcall pcase-0 x290 x296))))
            (let nil
              (error "wrong args"))))
        (setq list-297
              (cdr list-297)))
      (setq loopy-result
            (nreverse loopy-result))
      loopy-result)))
```

**Comment by okamsn** [comment] 2021-07-14 23:33
I think might have been caused by improperly binding the settings variables. If that was the only cause, then this should be fixed now.

Please check with the most recent version of the packages, if you get the chance.

**Comment by okamsn** [comment] 2021-08-29 01:16
No errors are detected by running the tests automatically for Emacs 27 using Github actions, so I'm closing this issue.

**Closed** 2021-08-29 01:16 UTC
Labels: bug, solved?
